export type ModelOpsResourceSpec = {
  name: string;
  cluster: string;
  instanceCount: number;
  workerNames: string[];
  routerReady: number;
  routerTotal: number;
  prefillReady: number;
  prefillTotal: number;
  decodeReady: number;
  decodeTotal: number;
  weight: number;
};

export const MODEL_OPS_RESOURCE_SPECS: ModelOpsResourceSpec[] = [
  {
    name: 'st-router-1',
    cluster: 'beijing-prod',
    instanceCount: 10,
    workerNames: Array.from({ length: 10 }, (_, index) => `st-router-1-inst-${index + 1}`),
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 4,
    prefillTotal: 4,
    decodeReady: 1,
    decodeTotal: 1,
    weight: 10,
  },
  {
    name: 'st-router-2',
    cluster: 'guangzhou-test',
    instanceCount: 2,
    workerNames: ['gz-l20-worker-003', 'gz-l20-worker-004'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 3,
    prefillTotal: 4,
    decodeReady: 1,
    decodeTotal: 1,
    weight: 10,
  },
  {
    name: 'st-router-3',
    cluster: 'guangzhou-test',
    instanceCount: 2,
    workerNames: ['gz-l20-worker-005', 'gz-l20-worker-006'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 2,
    prefillTotal: 2,
    decodeReady: 2,
    decodeTotal: 2,
    weight: 10,
  },
  {
    name: 'st-router-4',
    cluster: 'guangzhou-test',
    instanceCount: 2,
    workerNames: ['gz-l20-worker-007', 'gz-l20-worker-008'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 5,
    prefillTotal: 5,
    decodeReady: 1,
    decodeTotal: 2,
    weight: 10,
  },
  {
    name: 'h20-router-1',
    cluster: 'shanghai-online',
    instanceCount: 2,
    workerNames: ['nj-h20-worker-001', 'nj-h20-worker-002'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 6,
    prefillTotal: 6,
    decodeReady: 2,
    decodeTotal: 2,
    weight: 12,
  },
  {
    name: 'h20-router-2',
    cluster: 'shanghai-online',
    instanceCount: 2,
    workerNames: ['nj-h20-worker-003', 'nj-h20-worker-004'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 4,
    prefillTotal: 5,
    decodeReady: 1,
    decodeTotal: 1,
    weight: 12,
  },
  {
    name: 'h20-router-3',
    cluster: 'shanghai-online',
    instanceCount: 2,
    workerNames: ['nj-h20-worker-005', 'nj-h20-worker-006'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 3,
    prefillTotal: 3,
    decodeReady: 2,
    decodeTotal: 2,
    weight: 12,
  },
  {
    name: 'kp-router-1',
    cluster: 'wuhan-kunpeng',
    instanceCount: 2,
    workerNames: ['910b-kunpeng-worker-001', '910b-kunpeng-worker-002'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 2,
    prefillTotal: 2,
    decodeReady: 1,
    decodeTotal: 1,
    weight: 8,
  },
  {
    name: 'kp-router-2',
    cluster: 'wuhan-kunpeng',
    instanceCount: 2,
    workerNames: ['910b-kunpeng-worker-003', '910b-kunpeng-worker-004'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 1,
    prefillTotal: 2,
    decodeReady: 1,
    decodeTotal: 1,
    weight: 8,
  },
  {
    name: 'bj-router-1',
    cluster: 'beijing-prod',
    instanceCount: 2,
    workerNames: ['beijing-prod-worker-001', 'beijing-prod-worker-002'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 4,
    prefillTotal: 4,
    decodeReady: 1,
    decodeTotal: 1,
    weight: 7,
  },
  {
    name: 'bj-router-2',
    cluster: 'beijing-prod',
    instanceCount: 2,
    workerNames: ['beijing-prod-worker-003', 'beijing-prod-worker-004'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 5,
    prefillTotal: 6,
    decodeReady: 2,
    decodeTotal: 2,
    weight: 7,
  },
  {
    name: 'bj-router-3',
    cluster: 'beijing-prod',
    instanceCount: 2,
    workerNames: ['beijing-prod-worker-005', 'beijing-prod-worker-006'],
    routerReady: 1,
    routerTotal: 1,
    prefillReady: 3,
    prefillTotal: 3,
    decodeReady: 1,
    decodeTotal: 2,
    weight: 7,
  },
];

export const getModelOpsRoleSummary = (spec: ModelOpsResourceSpec) => ({
  router: `${spec.routerReady}/${spec.routerTotal}`,
  prefill: `${spec.prefillReady}/${spec.prefillTotal}`,
  decode: `${spec.decodeReady}/${spec.decodeTotal}`,
});
